<?php

/*
 * Module adds Mollie payment block.
 */


/**
 * Implements hook_menu().
 */
function sp_mollie_menu() {
  $items['donatie/%'] = array(
    'page callback' => 'sp_mollie_payment_landing_page',
    'page arguments' => array(1),
    'access callback' => TRUE,
  );
  $items['admin/config/sp_mollie'] = array(
    'title' => 'Mollie',
    'description' => 'Mollie instellingen.',
    'position' => 'right',
    'weight' => -20,
    'page callback' => 'system_admin_menu_block_page',
    'access callback' => 'sp_mollie_access_check',
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );

  $items['admin/config/sp_mollie/api-key'] = array(
    'title' => 'Mollie API key',
    'description' => 'Stel de Mollie API key in.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sp_mollie_api_settings_form'),
    'file' => 'sp_mollie_settings.form.inc',
    'access callback' => 'sp_mollie_access_check',
  );

  $items['admin/config/sp_mollie/landing-page'] = array(
    'title' => 'Mollie teksten landingspagina',
    'description' => 'Stel de feedback teksten voor de landingspagina in.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sp_mollie_landing_page_settings_form'),
    'file' => 'sp_mollie_settings.form.inc',
    'access callback' => 'sp_mollie_access_check',
  );

  $items['admin/config/sp_mollie/email'] = array(
    'title' => 'Mollie e-mail',
    'description' => 'Stel de Mollie e-mails in.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sp_mollie_email_settings_form'),
    'file' => 'sp_mollie_settings.form.inc',
    'access callback' => 'sp_mollie_access_check',
  );

  return $items;
}

/**
 * @return bool Has SPRBS configuration access
 */
function sp_mollie_access_check() {
  return (user_access('administer site configuration') || user_access('administer mollie'));
}

/**
 * Definces permission to administer mollie.
 */
function sp_mollie_permission() {
  return array(
    'administer mollie' => array(
      'title' => 'Beheer Mollie donatieknop',
      'description' => 'Stel de api-key, de e-mail, en landingspagina teksten voor de Mollie donatieknop in.',
    ),
  );
}


function sp_mollie_payment_landing_page($donation_id) {
  if (!empty($donation_id)) {
    // Get donation.
    $donation = sp_mollie_get_donation($donation_id);
    if (!empty($donation)) {
      // Get donation payment id.
      $payment_id = $donation->payment_id;
      if ($payment_id !== FALSE) {
        // Connect to mollie service.
        $mollie = sp_mollie_initialize();
        if ($mollie !== FALSE) {
          $payment  = $mollie->payments->get($payment_id);
          // Store donation status.
          $donation->status = $payment->status;
          entity_save('sp_mollie_donation', $donation);
          // Create feedback.
          if ($payment->isPaid() == TRUE) {
            $content = variable_get('sp_mollie_feedback_is_paid',  '<p>Dank, uw donatie is ontvangen.</p>');
            // Send email.
            if (webform_valid_email_address($donation->email)) {
              $body_raw = variable_get('sp_mollie_email_body',  array());
              $body = check_markup($body_raw['value'], $body_raw['format']);
              $subject = variable_get('sp_mollie_email_subject', '');
              $replacements = array(
                '[name]' => $donation->name,
                '[email]' => $donation->email,
                '[phone]' => $donation->phone,
                '[amount]' => $donation->amount,
                '[payment_id]' => $donation->payment_id,
                '[donation_id]' => $donation->did,
              );
              foreach ($replacements as $token => $value) {
                $value_clean = check_plain($value);
                if (!empty($value)) {
                  $body = str_replace($token, $value_clean, $body);
                  $subject = str_replace($token, $value_clean, $subject);
                }
              }
              $site_mail = variable_get('site_mail', ini_get('sendmail_from'));
              $from = variable_get('sp_mollie_email_from', $site_mail);
              $params = array(
                'subject' => $subject,
                'body' => $body,
              );
              $message = drupal_mail('sp_mollie', 'donation_email', $donation->email, language_default(), $params, $from);
            }
          }
          else if ($payment->isOpen() == FALSE) {
            $content = variable_get('sp_mollie_feedback_is_cancelled',  '<p>Helaas, de betaling van uw donatie is geannuleerd.</p>');
          }
          else {
            $content = variable_get('sp_mollie_feedback_is_open',  '<p>De betaling van uw donatie is op dit moment nog niet afgerond.</p>');
          }
        }
        else {
          $content = variable_get('sp_mollie_feedback_error',  '<p>Helaas, er is iets misgegaan met het ophalen van uw donatiegegevens.</p>');
        }
      }
      else {
        $content = variable_get('sp_mollie_feedback_no_id',  '<p>Helaas, er is iets misgegaan met het ophalen van uw donatiegegevens.</p>');
      }
    }
    else {
      $content = '<p>Er is een fout opgetreden.</p>';
    }
  }
  else {
    $content = '<p>Er is een fout opgetreden.</p>';
  }
  return '<div class="content-wrap">' . $content . '</div>';
}

/**
 * Implements hook_entity_info().
 */
function sp_mollie_entity_info() {
  $info = array();
  $info['sp_mollie_donation'] = array(
    'label' => 'Mollie donation',
    'entity class' => 'Entity',
    'controller class' => 'EntityAPIController',
    'base table' => 'sp_mollie_donation',
    'entity keys' => array(
      'id' => 'did',
    ),
    'fieldable' => FALSE,
  );
  return $info;
}

/**
 * Implements hook_entity_property_info_alter().
 */
function sp_mollie_entity_property_info_alter(&$info) {
  $properties = &$info['sp_mollie_donation']['properties'];

  foreach (array_keys($properties) as $key) {
    if ($key == 'did') {
      continue;
    }
    $properties[$key] += array(
      'setter callback' => 'entity_property_verbatim_set',
    );
  }
}

/**
* Implements hook_block_info().
*/
function sp_mollie_block_info() {
  $blocks = array();
  $blocks['sp_mollie'] = array(
    'info' => 'SP Mollie',
  );
  return $blocks;
}

/**
* Implements hook_block_view().
*/
function sp_mollie_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'sp_mollie':
      $block['subject'] = 'online doneren';
      $block['content'] = drupal_get_form('sp_mollie_payment_form');
      break;
  }
  return $block;
}

function sp_mollie_payment_form($form, &$form_state) {
  $form['#prefix'] = '<div id="sp-mollie-form">';
  $form['#suffix'] = '</div>';
  if (empty($form_state['storage']['sp_mollie_form_page'])) {
    // Donation
    $form['page_1_submit'] = array(
      '#type' => 'button',
      '#value' => 'Doneer',
      '#ajax' => array(
        'callback' => 'sp_mollie_payment_form_callback',
        'wrapper' => 'sp-mollie-form',
        'method' => 'replace',
        'effect' => 'fade',
      ),
    );
  }
  elseif ($form_state['storage']['sp_mollie_form_page'] === 2) {
    $amounts = array(
      '5.00' => '5,00 €',
      '10.00' => '10,00 €',
      '25.00' => '25,00 €',
      'free_amount' => 'Anders',
    );
    $form['amount'] = array(
      '#type' => 'radios',
      '#title' => 'Bedrag',
      '#options' => $amounts,
      '#required' => TRUE,
    );
    $form['free_amount'] = array(
      '#type' => 'textfield',
      '#title' => 'Bedrag',
      '#states' => array(
        'visible' => array(
          ':input[name="amount"]' => ['value' => 'free_amount'],
        ),
      ),
    );
    $form['page_2_submit'] = array(
      '#type' => 'button',
      '#value' => 'Ga verder',
      '#ajax' => array(
        'callback' => 'sp_mollie_payment_form_callback',
        'wrapper' => 'sp-mollie-form',
        'method' => 'replace',
        'effect' => 'fade',
      ),
    );
  }
  elseif ($form_state['storage']['sp_mollie_form_page'] === 3) {

    $form['name'] = array(
      '#type' => 'textfield',
      '#title' => 'Naam',
      '#required' => TRUE,
    );
    $form['email'] = array(
      '#type' => 'textfield',
      '#title' => 'E-mailadres',
      '#required' => TRUE,
    );
    $form['phone'] = array(
      '#type' => 'textfield',
      '#title' => 'Telefoonnummer',
    );
    $form['page_3_submit'] = array(
      '#type' => 'button',
      '#value' => 'Ga verder',
      '#ajax' => array(
        'callback' => 'sp_mollie_payment_form_callback',
        'wrapper' => 'sp-mollie-form',
        'method' => 'replace',
        'effect' => 'fade',
      ),
    );
  }
  elseif ($form_state['storage']['sp_mollie_form_page'] === 4) {

    // Initialize mollie.
    $mollie = sp_mollie_initialize();
    if ($mollie !== FALSE) {
      // Get issuers.
      $issuers = $mollie->issuers->all();
      foreach ($issuers as $issuer) {
        if ($issuer->method == Mollie_API_Object_Method::IDEAL) {
          $options[$issuer->id] = $issuer->name;
        }
      }
      $form['issuer'] = array(
        '#type' => 'radios',
        '#title' => 'Kies uw bank',
        '#options' => $options,
        '#required' => TRUE,
      );
      $form['page_4_submit'] = array(
        '#type' => 'submit',
        '#value' => 'Ga naar uw bank',
      );
    }
    else {
      $form['error'] = array(
        '#markup' => '<p>Door een storing is het tijdelijk niet mogelijk om donaties te doen.</p>',
      );
    }
  }
  return $form;
}

function sp_mollie_payment_form_validate($form, &$form_state) {
  if (empty($form_state['storage']['sp_mollie_form_page'])) {
    $form_state['storage']['sp_mollie_form_page'] = 1;
  }

  switch ($form_state['storage']['sp_mollie_form_page']) {
    case 1:
      $form_state['storage']['sp_mollie_form_page'] = 2;
      break;
      
    case 2:
      $amount = $form_state['values']['amount'];
      if ($amount === 'free_amount') {
        $amount = $form_state['values']['free_amount'];
      }
      $regex = '#^[^0-9]*([0-9]+)[,.]?([0-9]{2}|-)?[^0-9]*$#';
      if (preg_match($regex, $amount, $matches)) {
        $euros = $matches[1];
        if ($matches[2] == '-' || empty($matches[2])) {
          $cents = '00';
        }
        else {
          $cents = $matches[2];
        }
        $amount = $euros . '.' . $cents;
        $form_state['storage']['sp_mollie_amount'] = $amount;
        $form_state['storage']['sp_mollie_form_page'] = 3;
      }
      else {
        form_set_error('free_amount', "Kies een bedrag in euro's");
      }
      break;
    
    case 3:
      if (!empty($form_state['values']['name'])) {
        $form_state['storage']['name'] = $form_state['values']['name'];
      }
      else {
        $form_state['storage']['name'] = '';
      }
      if (!empty($form_state['values']['phone'])) {
        $form_state['storage']['phone'] = $form_state['values']['phone'];
      }
      else {
        $form_state['storage']['phone'] = '';
      }
      if (!empty($form_state['values']['email'])) {
        if (valid_email_address($form_state['values']['email'])) {
          $form_state['storage']['email'] = $form_state['values']['email'];
        }
        else {
          form_set_error('email', 'Vul een geldig e-mailadres in');
          return;
        }
      }
      else {
        $form_state['storage']['email'] = '';
      }
      $form_state['storage']['sp_mollie_form_page'] = 4;
      break;

    case 4:
      break;
  }
}

function sp_mollie_payment_form_submit($form, &$form_state) {
  global $base_url;
  // Initialize mollie.
  $mollie = sp_mollie_initialize();
  if ($mollie !== FALSE) {
    try {
      $donation = sp_mollie_create_donation();
      $payment = $mollie->payments->create(array(
        "amount"      => $form_state['storage']['sp_mollie_amount'],
        "description" => "Donatie www.sp.nl/doneren",
        "redirectUrl" => $base_url . '/donatie/' . $donation->did,
        "method" => Mollie_API_Object_Method::IDEAL,
        "issuer" => $form_state['values']['issuer'], // e.g. "ideal_INGBNL2A"
        "metadata" => array(
          "donation_id" => $donation->did,
        ),
      ));
    }
    catch (exception $e) {
      drupal_set_message('Het was helaas niet mogelijk om een verbinding te maken met de betaaldienst. Probeert u het op een later moment nog eens.', 'error');
      return;
    }
    // To do: store payment id with order id, to retreive it on the landing page.
    $donation->payment_id = $payment->id;
    $donation->amount = 100 * $form_state['storage']['sp_mollie_amount'];
    $donation->name = $form_state['storage']['name'];
    $donation->email = $form_state['storage']['email'];
    $donation->phone = $form_state['storage']['phone'];
    $result = entity_save('sp_mollie_donation', $donation);

    drupal_goto($payment->links->paymentUrl, array(), 307);
  }
  else {
    form_set_error('issuer', 'Er is een tijdelijke storing.');
  }
}

function sp_mollie_payment_form_callback($form, &$form_state) {
  $form_state['rebuild'] = TRUE;
  return $form;
}

function sp_mollie_initialize() {
  try {
  module_load_include('php', 'sp_mollie', '/includes/Mollie/API/Autoloader');
  $mollie = new Mollie_API_Client;
  $mollie->setApiKey(variable_get('sp_mollie_api_key', "test_61lRKc1ZV8CHecChTTrG94O5AimOz5"));
  }
  catch (exception $e) {
    watchdog('sp_mollie', 'Het was helaas niet mogelijk om een verbinding te maken met Mollie: ' . $e->getMessage());
    return FALSE;
  }
  return $mollie;
}

function sp_mollie_get_donation($donation_id) {
  $donation = entity_load_single('sp_mollie_donation', $donation_id);
  return $donation;
}

function sp_mollie_create_donation() {
  // Create new donation.
  $donation = entity_create('sp_mollie_donation', array('date' => time()));
  $result = entity_save('sp_mollie_donation', $donation);
  if ($result) {
    return $donation;
  }
  return FALSE;
}

function sp_mollie_mail($key, &$message, $params) {
  switch ($key) {
  case 'test_email':
    $message['subject'] = $params['sp_mollie_email_subject']; 
    $message['body'][] = check_markup($params['sp_mollie_email_body']['value'], $params['sp_mollie_email_body']['format']); 
    break;
  case 'donation_email':
    $message['subject'] = $params['subject']; 
    $message['body'][] = $params['body']; 
    break;
  }
}
